# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    filter_sets:
        cache: ~

        # the name of the "filter set"
        thumb_small:

            # adjust the image quality to 75%
            quality: 75

            # list of transformations to apply (the "filters")
            filters:

                # create a thumbnail: set size to 120x90 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail: { size: [200, 200], mode: outbound ,allow_upscale: true}

        thumb_background:

                # adjust the image quality to 75%
                quality: 75

                # list of transformations to apply (the "filters")
                filters:
                    thumbnail: { size: [300, 300], mode: outbound , allow_upscale: true}